apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf2word-deployment
  labels:
    app: pdf2word
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf2word
  template:
    metadata:
      labels:
        app: pdf2word
    spec:
      containers:
        - name: pdf2word-container
          image: pdf2word-service:latest   # Use local image name
          imagePullPolicy: Never           # Important to avoid pulling from Docker Hub
          ports:
            - containerPort: 50002
          env:
            - name: FLASK_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: pdf2word-service
spec:
  selector:
    app: pdf2word
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50002
      nodePort: 30002
