apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf2word-deployment
  labels:
    app: pdf2word
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf2word
  template:
    metadata:
      labels:
        app: pdf2word
    spec:
      containers:
        - name: pdf2word-container
          image: manoharshetty507/pdf2word-service:latest
          ports:
            - containerPort: 5001
          env:
            - name: FLASK_ENV
              value: "production"

---
apiVersion: v1
kind: Service
metadata:
  name: pdf2word-service
spec:
  selector:
    app: pdf2word
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP
