apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: yourdockerhubusername/flask-gateway:latest
        ports:
        - containerPort: 5000
        env:
        - name: PDF_SERVICE_URL
          value: "http://pdf-service:5001"
        - name: YTDL_SERVICE_URL
          value: "http://yt-service:5002"
        - name: AUDIO_SERVICE_URL
          value: "http://audio-service:5003"
        - name: MUSIC_SERVICE_URL
          value: "http://music-service:5004"
        - name: WORD2PDF_SERVICE_URL
          value: "http://word2pdf-service:5005"

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort  # Change to NodePort if you don't use a cloud provider
